#!/bin/bash
echo "etcd init..."
echo "etcd put /yun/admin_api/gorm"
etcdctl put /yun/admin_api/gorm "{\"debug\": true,\"db_type\":\"mysql\",\"max_lifetime\":7201,\"max_open_conns\":20,\"max_idle_conns\":5,\"table_prefix\":\"yun_\"}"
echo "etcd put /yun/admin_api/web"
etcdctl put /yun/admin_api/web "{\"static_path\": \"/var/www/html/\",\"port\": 9992,\"domain\": \"127.0.0.1:9992\",\"read_timeout\": 5,\"write_timeout\": 5,\"idle_timeout\": 5,\"prefix\": \"/api\"}"
echo "etcd put /yun/system/config/mysql"
etcdctl put /yun/system/config/mysql "{\"host\": \"mysql:3306\",\"password\": \"root\",\"database\": \"yun_sms\",\"user\": \"root\",\"charset\": \"utf8mb4\",\"maxOpenConns\": 10,\"maxIdleConns\": 2}"
echo "etcd put /yun/system/config/redis"
etcdctl put /yun/system/config/redis "{\"host\": \"redis:6379\",\"password\": \"\",\"database\": 0,\"maxOpenConns\": 10,\"maxIdleConns\": 2}"
echo "etcd put /yun/system/config/nsq"
etcdctl put /yun/system/config/nsq "{\"host\": \"nsqd:4150\"}"
echo "etcd put /yun/system/config/etcd_admin"
etcdctl put /yun/system/config/etcd_admin "{\"host\": \"http://127.0.0.1:4171/etcdkeeper\"}"
echo "etcd put /yun/system/config/nsq_admin"
etcdctl put /yun/system/config/nsq_admin "{\"host\": \"http://127.0.0.1:4171\"}"
echo "etcd put /yun/system/config/phonedata"
etcdctl put /yun/system/config/phonedata "\"/phonedata.txt\""
echo "etcd put /yun/system/config/cron/stat"
etcdctl put /yun/system/config/cron/stat "\"0 */5 * * * *\""
echo "etcd put /yun/system/config/cron/querysr"
etcdctl put /yun/system/config/cron/querysr "\"*/10 * * * * *\""
echo "etcd put /yun/system/config/cron/querymo"
etcdctl put /yun/system/config/cron/querymo "\"*/30 * * * * *\""